package com.taras.secondapplication;

import android.app.Application;
import android.test.ApplicationTestCase;

/**
 * This is autogenerated class. I dont created him
 */
public class ApplicationTest extends ApplicationTestCase<Application> {
    public ApplicationTest() {
        super(Application.class);
    }
}